### ISSUE TITLE
[✨FEATURE] feedback: SelectUserTypePage - 유저 타입(학생/선생님) 선택 페이지

### ISSUE THREAD

**Issue by otcroz** [DS-Narsha/front-end#26]
**기능 요청이 문제와 관련이 있습니까? 설명해주세요.**
유저 타입(학생/선생님) 선택 페이지 작성 페이지 피드백 요청
- commit 내용: 488836b855e94d0fdbdf898810b9afae4cf59c78

**원하는 솔루션 설명**
- **피드백**
- [x] stylesheet 속성 이름 수정 필요
    
    속성 이름에 숫자를 넣는 것은 추천하지 않습니다. 어떤 범위를 스타일로 적용하고 있는지 최대한 **명사형**으로 특정해주세요.
    ⇒ ex) container2 → contentBox

- [x]  선생님, 학생 선택 버튼에 elevation(그림자) 주기, 아래 코드 참고
```css
shadowOffset: {
        width: 0,
        height: 3,
      },
      elevation: 5,
```

**고려한 대안을 설명하세요**
x
